# Generated by Django 4.1.4 on 2023-05-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('lien', models.TextField()),
                ('marque', models.CharField(max_length=50)),
                ('prix', models.FloatField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Number',
        ),
    ]
